Revert "testing removing some fields backend"
This reverts commit 7db5e3c3fabfd347395becf3a17135eef7a4183e.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -229,29 +229,29 @@ jobs:
             sudo apt-get -y -qq update
             sudo apt-get -y -qq install python3
             sudo apt-get -qq install awscli
-      # - run:
-      #     name: Adding .env data
-      #     command: |
-      #       touch backend/.env
-      #       echo NODE_ENV=$ENVIRONMENT >> "backend/.env"
-      #       echo VERSION=${CIRCLE_WORKFLOW_ID:0:7} >> "backend/.env"
-      #       echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> "backend/.env"
-      #       echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> "backend/.env"
-      #       echo TYPEORM_ENTITIES=.$TYPEORM_ENTITIES >> "backend/.env"
-      #       echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> "backend/.env"
-      #       echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-      #       echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-      #       echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-      #       echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-      #       echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-      #       cd backend
-      #       cat .env
+      - run:
+          name: Adding .env data
+          command: |
+            touch backend/.env
+            echo NODE_ENV=$ENVIRONMENT >> "backend/.env"
+            echo VERSION=${CIRCLE_WORKFLOW_ID:0:7} >> "backend/.env"
+            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> "backend/.env"
+            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> "backend/.env"
+            echo TYPEORM_ENTITIES=.$TYPEORM_ENTITIES >> "backend/.env"
+            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> "backend/.env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+            cd backend
+            cat .env
       - run:
           name: Run migrations
           command: |
             cd backend 
             npm install
-            # npm run build
+            npm run build
             npm run migrations > migrations_log.txt
             cat migrations_log.txt
       - run:
@@ -322,23 +322,23 @@ jobs:
             URLS=$(curl -H "token: 5c64246e-cafb-4e5b-a96b-23b44084375c" --request GET https://api.memstash.io/values/url_${CIRCLE_WORKFLOW_ID:0:7})
             echo $URLS >> inventory.txt
             cat inventory.txt
-      # - run:
-      #     name: Adding .env data
-      #     command: |
-      #       touch backend/.env
-      #       echo NODE_ENV=$ENVIRONMENT >> "backend/.env"
-      #       echo VERSION=${CIRCLE_WORKFLOW_ID:0:7} >> "backend/.env"
-      #       echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> "backend/.env"
-      #       echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> "backend/.env"
-      #       echo TYPEORM_ENTITIES=.$TYPEORM_ENTITIES >> "backend/.env"
-      #       echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> "backend/.env"
-      #       echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-      #       echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-      #       echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-      #       echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-      #       echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-      #       cd backend
-      #       cat .env
+      - run:
+          name: Adding .env data
+          command: |
+            touch backend/.env
+            echo NODE_ENV=$ENVIRONMENT >> "backend/.env"
+            echo VERSION=${CIRCLE_WORKFLOW_ID:0:7} >> "backend/.env"
+            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> "backend/.env"
+            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> "backend/.env"
+            echo TYPEORM_ENTITIES=.$TYPEORM_ENTITIES >> "backend/.env"
+            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> "backend/.env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+            cd backend
+            cat .env
 
       - run:
           name: Compress Backend
@@ -374,8 +374,14 @@ jobs:
             export ENDPOINT_URL="http://$BACKEND_URL:3030/api/status"
             echo $ENDPOINT_URL
             curl $ENDPOINT_URL
-            curl -s ${ENDPOINT_URL}
-            
+            if curl -s ${ENDPOINT_URL} | grep "ok"
+            then
+              echo "Success"
+              exit 0
+            else
+              echo "Failed"
+              exit 1
+            fi  
       - run:
           name: Frontend smoke test.
           command: |
